name: CI input output kernels 

on:
  push:
    branches:
      - main
    paths:
      - 'src/cb.txt'

permissions:
    contents: write

jobs:
  job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: run code
        run: |
          # ---------------------------------------
          FILE_TEXT="$(cat src/cb.txt)"
          echo "FILE_TEXT = $FILE_TEXT";
          rm -rf src/cb.txt;
          # ---------------------------------------
          CODE=$(echo "$FILE_TEXT" | cut -d '|' -f 1)
          echo "CODE = $CODE";
          # ---------------------------------------
          KERNEL=$(echo "$FILE_TEXT" | cut -d '|' -f 2)
          echo "KERNEL = $KERNEL";
          # ---------------------------------------
          
          echo "GITHUB_WORKSPACE - ${{ github.workspace }}";
          # ---------------------------------------
          if [ -f "$KERNEL" == "python" ]; then
            # -------------------
            # Parse the text and save to out.py
            echo $CODE  > out.py;
            # -------------------
            # Print out.py
            echo "out.py";
            cat out.py;
            # -------------------
            # Run the code in out.py
            # OUTPUT="$(python '${{ github.workspace }}/out.py')";
            # Save the output in a file
            # echo "$OUTPUT" > output.txt;
            # Print the output
            # echo "OUTPUT = $OUTPUT";
            # -------------------
            # OR
            # -------------------
            # Run the code in out.py, Save the output in a file
            python out.py > output.txt;
            # Print the output
            echo "OUTPUT";
            cat output.txt;
            # -------------------
            
            
          elif [ -f "$KERNEL" == "javascript" ]; then
            echo "javascript";
          elif [ -f "$KERNEL" == "matlab" ]; then
            echo "matlab";
          fi;
          # ---------------------------------------
          repoOwner=$(echo "${{ github.repository }}" | cut -d '/' -f 1);
          repoName=$(echo "${{ github.repository }}" | cut -d '/' -f 2);
          repoOwnerEmail="j622amilah@gmail.com";
          git config --global user.email ${repoOwnerEmail};
          git config --global user.name ${repoOwner};
          git pull origin main;
          git checkout main;
          git branch --set-upstream-to origin/main;
          git merge main --ff-only;
          git add output.txt /home/runner/work/$repoName/$repoName/src/cb.txt; 
          git diff-index --quiet HEAD || git commit -m "add files" --allow-empty;
          git push;
          # ---------------------------------------
