name: run code 

on:
  workflow_dispatch:

permissions:
    contents: write

jobs:
  job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - run: |
          import os;
          print('test')
