name: run code 

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
    contents: write

jobs:
  job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: run code
        run: |
          # sudo pip install -U tensorflow;
          # Import libraries
          # import tensorflow as tf;
          cat > out.py << EOF
          import os; import sys; from PIL import Image; import numpy as np; import requests;
          def functionName(x):
            return x * 2;
          print(functionName(4));
          EOF
          python out.py;

          
          
