name: run code 

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
    contents: write

jobs:
  job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: run code
        run: |
          # sudo pip install -U tensorflow;
          # Import libraries
          # import tensorflow as tf;
          python -c "import os; import sys; from PIL import Image; import numpy as np; import requests; def fetch_an_image(url, desired_file_name): response = requests.get(url); 
          with open(desired_file_name, 'wb') as file:
            file.write(response.content);
          url = 'https://storage.googleapis.com/memetics-motivation/success_512x512_0.png'; desired_file_name = 'image_to_receive_a_style.png'; fetch_an_image(url, desired_file_name); ";

          
          
